# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # main branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /samples/dotnet
    schedule:
      interval: daily

  # 2.x.x branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "2.x.x"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: "2.x.x"

  - package-ecosystem: nuget
    directory: /samples/dotnet
    schedule:
      interval: daily
    target-branch: "2.x.x"
